# Generated by Django 4.1.1 on 2023-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='Фото для карточки')),
                ('photo_big', models.ImageField(upload_to='photos_big/%Y/%m', verbose_name='Фото большое')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Автор')),
                ('content', models.CharField(max_length=255, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('col_1_1', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №1')),
                ('col_1_2', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №2')),
                ('col_1_3', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №3')),
                ('col_1_4', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №4')),
                ('col_1_5', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №5')),
                ('col_1_6', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №6')),
                ('col_1_7', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №7')),
                ('col_2_1', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №1')),
                ('col_2_2', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №2')),
                ('col_2_3', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №3')),
                ('col_2_4', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №4')),
                ('col_2_5', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №5')),
                ('col_2_6', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №6')),
                ('col_2_7', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №7')),
                ('col_3_1', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №1')),
                ('col_3_2', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №2')),
                ('col_3_3', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №3')),
                ('col_3_4', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №4')),
                ('col_3_5', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №5')),
                ('col_3_6', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №6')),
                ('col_3_7', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №7')),
                ('col_4_1', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №1')),
                ('col_4_2', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №2')),
                ('col_4_3', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №3')),
                ('col_4_4', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №4')),
                ('col_4_5', models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №5')),
                ('col_4_6', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №6')),
                ('col_4_7', models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №7')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.CharField(max_length=20, verbose_name='Продолжительность')),
                ('quantity', models.CharField(max_length=20, verbose_name='Количество фото')),
                ('note', models.CharField(max_length=40, verbose_name='Примечание')),
                ('desc', models.TextField(null=True, verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
