# Generated by Django 4.1.1 on 2022-09-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemodel',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
    ]
