# Generated by Django 4.1.1 on 2022-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_pricemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='photo_big',
            field=models.ImageField(null=True, upload_to='photos_big/%Y/%m', verbose_name='Фото большое'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m', verbose_name='Фото для карточки'),
        ),
    ]
