# Generated by Django 4.1.1 on 2022-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blogmodel_photo_big_alter_blogmodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('col_1_1', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №1')),
                ('col_1_2', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №2')),
                ('col_1_3', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №3')),
                ('col_1_4', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №4')),
                ('col_1_5', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №5')),
                ('col_1_6', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №6')),
                ('col_1_7', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка1 №7')),
                ('col_2_1', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №1')),
                ('col_2_2', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №2')),
                ('col_2_3', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №3')),
                ('col_2_4', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №4')),
                ('col_2_5', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №5')),
                ('col_2_6', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №6')),
                ('col_2_7', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка2 №7')),
                ('col_3_1', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №1')),
                ('col_3_2', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №2')),
                ('col_3_3', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №3')),
                ('col_3_4', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №4')),
                ('col_3_5', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №5')),
                ('col_3_6', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №6')),
                ('col_3_7', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка3 №7')),
                ('col_4_1', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №1')),
                ('col_4_2', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №2')),
                ('col_4_3', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №3')),
                ('col_4_4', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №4')),
                ('col_4_5', models.ImageField(upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №5')),
                ('col_4_6', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №6')),
                ('col_4_7', models.ImageField(null=True, upload_to='photos_portfolio/<django.db.models.fields.CharField>', verbose_name='колонка4 №7')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='photo_big',
            field=models.ImageField(upload_to='photos_big/%Y/%m', verbose_name='Фото большое'),
        ),
    ]
