# Generated by Django 4.1.1 on 2022-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_portfoliomodel_alter_blogmodel_photo_big'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_1',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_2',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №2'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_3',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №3'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_4',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №4'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_5',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №5'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_6',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №6'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_1_7',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка1 №7'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_1',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_2',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №2'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_3',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №3'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_4',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №4'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_5',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №5'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_6',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №6'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_2_7',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка2 №7'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_1',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_2',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №2'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_3',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №3'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_4',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №4'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_5',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №5'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_6',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №6'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_3_7',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка3 №7'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_1',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_2',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №2'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_3',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №3'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_4',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №4'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_5',
            field=models.ImageField(upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №5'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_6',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №6'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='col_4_7',
            field=models.ImageField(null=True, upload_to='photos_portfolio/%Y/%m', verbose_name='колонка4 №7'),
        ),
    ]
