# Generated by Django 4.1.1 on 2022-09-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
