# Generated by Django 4.1.1 on 2022-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemodel',
            name='desc',
            field=models.TextField(null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name=''),
        ),
    ]
